name: "Run kubeconform"
description: "Easy to use kubeconform action"
author: "hermanbanken"
inputs:
  args:
    description: "cli arguments to pass to kubeconform"
    default: "."
    required: false
  version:
    description: "which version of kubeconform to use"
    default: "v0.5.0"
    required: false
runs:
  using: "node16"
  main: "dist/run/index.js"
branding:
  icon: "shield"
  color: "yellow"
